create table insurance_claim3 (
"months_as_customer" int,
"age" int,
"policy_number" int, 
"policy_bind_date" date,
"policy_state" varchar,
"policy_csl" varchar,
"policy_deductable" int,
"policy_annual_premium" varchar,
"umbrella_limit" int,
"insured_zip" int,
"insured_sex" varchar,
"insured_education_level" varchar,
"insured_occupation" varchar,
"insured_hobbies" varchar,
"insured_relationship" varchar,	
"capital-gains" int,
"capital-loss" int,
"incident_date"	date,
"incident_type" varchar,
"collision_type" varchar,
"incident_severity" varchar,
"authorities_contacted" varchar,
"incident_state" varchar,
"incident_city" varchar,
"incident_location" varchar,
"incident_hour_of_the_day" int,
"number_of_vehicles_involved" int,
"property_damage" varchar,
"bodily_injuries" int,	
"witnesses" int,
"police_report_available" varchar,
"total_claim_amount" int,
"injury_claim" int,
"property_claim" int,
"vehicle_claim" int,
"auto_make" varchar,
"auto_model" varchar,
"auto_year" int,
"fraud_reported" varchar,
"_c39" varchar
	)
	
SELECT * FROM insurance_claim3